FROM python:3.10-slim

#set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

#set working directory
WORKDIR /app

#COPY Project files 
COPY . .

#install dependencies 
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

#expose ports 
EXPOSE 8501

#runstreamlit
CMD ["streamlit", "run", "app.py","--server.port=8501", "--server.enableCORS=false"]
